name: Tests

on:
  pull_request:
    branches: '*'

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch, tag or SHA to release from'
        required: true
        default: 'master'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies
        run: python -m pip install pytest

      - name: Install current version of the clamd package
        run: python -m pip install -e .

      - name: Install and update clamav engine
        run: sudo apt update
        run: sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs --yes
        run: sudo freshclam --verbose
        run: systemctl restart clamav-daemon.service

      - name: Run unit tests
        run: pytest
